//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。

//     已作适用性更改
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 
namespace HW.PMS.SubDis.Service.Proxies.Obsoleted
{


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "BoTaoAdapterSoap", Namespace = "http://tempuri.org/")]
public partial class AdapterProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CallAdapterOperationCompleted;
    private string FuncName;
    /// <remarks/>
    public AdapterProxy() {
        this.Url = "";//"http://124.127.242.67/ARIAdapterProject/BoTaoAdapter.asmx";
    }
    public AdapterProxy(string url,string funcName)
    {
        this.Url = url;
        this.FuncName = funcName;
    }
    public void setURL(string url)
    {
        this.Url = url;
    }
    /// <remarks/>
    public event CallAdapterCompletedEventHandler CallAdapterCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BoTao_ARI_Send", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Result CallAdapter(Verify verify) {
        object[] results = this.Invoke(FuncName, new object[] {
                    verify});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCallAdapter(Verify verify, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke(FuncName, new object[] {
                    verify}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndCallAdapter(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void CallAdapterAsync(Verify verify)
    {
        this.CallAdapterAsync(verify, null);
    }
    
    /// <remarks/>
    public void CallAdapterAsync(Verify verify, object userState)
    {
        if ((this.CallAdapterOperationCompleted == null))
        {
            this.CallAdapterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallAdapterOperationCompleted);
        }
        this.InvokeAsync(FuncName, new object[] {
                    verify}, this.CallAdapterOperationCompleted, userState);
    }

    private void OnCallAdapterOperationCompleted(object arg)
    {
        if ((this.CallAdapterCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallAdapterCompleted(this, new CallAdapterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Verify {
    
    private string timeStampField;
    
    private string encryptedStrField;
    
    /// <remarks/>
    public string TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public string EncryptedStr {
        get {
            return this.encryptedStrField;
        }
        set {
            this.encryptedStrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Result {
    
    private string mesField;
    
    private bool retField;
    
    /// <remarks/>
    public string mes {
        get {
            return this.mesField;
        }
        set {
            this.mesField = value;
        }
    }
    
    /// <remarks/>
    public bool ret {
        get {
            return this.retField;
        }
        set {
            this.retField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void CallAdapterCompletedEventHandler(object sender, CallAdapterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallAdapterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    internal CallAdapterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}


}